% Tcq definition
ascq(eqr,se).
ascq(eqr,sf).
ascq(eqr,sexp).

attack(
tcq(
[se([treatment(T), may_cause_complication(T,C)],not_recommend(T)),
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
challenges(se,eqr)],
attacks(
se([treatment(T), may_cause_complication(T,C)],not_recommend(T)),
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))))) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(se([treatment(T), may_cause_complication(T,C)],not_recommend(T))), ascq(eqr,se).

attack(
tcq(
[sf([fields(F1,F2), more_relevant(F1,F2)],relevant_field(F1)),
eqr([current_state(R1,R2,R3), expert(E), field(F2), recommends(E,F2,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
challenges(sf,eqr)],
attacks(
sf([fields(F1,F2), more_relevant(F1,F2)],relevant_field(F1)),
eqr([current_state(R1,R2,R3), expert(E), field(F2), recommends(E,F2,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
))) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F2), recommends(E,F2,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(sf([fields(F1,F2), more_relevant(F1,F2)],relevant_field(F1))), ascq(eqr,sf).

attack(
tcq(
[sexp([experts(E1,E2), more_reliable(E1,E2)],reliable_expert(E1)),
eqr([current_state(R1,R2,R3), expert(E2), field(F), recommends(E2,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
challenges(sexp,eqr)],
attacks(
sexp([experts(E1,E2), more_reliable(E1,E2)],reliable_expert(E1)),
eqr([current_state(R1,R2,R3), expert(E2), field(F), recommends(E2,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
))) :- arg(eqr([current_state(R1,R2,R3), expert(E2), field(F), recommends(E2,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(sexp([experts(E1,E2), more_reliable(E1,E2)],reliable_expert(E1))), ascq(eqr,sexp).

% ALT scheme definition

attack(
alt(
[eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T1), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T2), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
alternative(T1,T2)
],
attacks(
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T1), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)),
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T2), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
))) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T1), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T2), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), alternative(T1,T2).


% for AF figure generation
% optional
% attack between se -> eqr
att(
se([treatment(T), may_cause_complication(T,C)],not_recommend(T)),
eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(se([treatment(T), may_cause_complication(T,C)],not_recommend(T))), ascq(eqr,se).

% attack between sf -> eqr
att(
sf([fields(F1,F2), more_relevant(F1,F2)],relevant_field(F1)),
eqr([current_state(R1,R2,R3), expert(E), field(F2), recommends(E,F2,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F2), recommends(E,F2,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(sf([fields(F1,F2), more_relevant(F1,F2)],relevant_field(F1))), ascq(eqr,sf).

% attack between sexp -> eqr
att(
sexp([experts(E1,E2), more_reliable(E1,E2)],reliable_expert(E1)),
eqr([current_state(R1,R2,R3), expert(E2), field(F), recommends(E2,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))
) :- arg(eqr([current_state(R1,R2,R3), expert(E2), field(F), recommends(E2,F,T), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(sexp([experts(E1,E2), more_reliable(E1,E2)],reliable_expert(E1))), ascq(eqr,sexp).

% attack generation -- alternative recommendations attack each other
att(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T1), new_state(S), goal(G), promotes(G,V)],reachable_goal(G)), eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T2), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))) :- arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T1), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), arg(eqr([current_state(R1,R2,R3), expert(E), field(F), recommends(E,F,T2), new_state(S), goal(G), promotes(G,V)],reachable_goal(G))), alternative(T1,T2).
